# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Wx-Perl-FSHandler-UNC
version:      1.008
version_from: lib/Wx/Perl/FSHandler/UNC.pm
installdirs:  site
requires:
    IO::File:                      0
    Test::More:                    0
    Wx:                            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
